version: '3.6'

services:
  kafka_exporter:
    image: danielqsj/kafka-exporter:v1.6.0
    ports:
      - 8080:8080
    command: --web.listen-address=0.0.0.0:8080 --kafka.server=kafka:9092
    # command: --web.listen-address=0.0.0.0:8080 --kafka.server=10.20.1.99:9092
    depends_on:
      - kafka

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9999:9999'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_com_sun_management_jmxremote=true
      - KAFKA_CFG_com_sun_management_jmxremote_port=9999
