---
wireguard_interfaces:
  - name: 'wg0'
    address: '10.9.0.1/24'
    listen_port: '51820'
    private_key: 'IBP8Ch7d7hN7CNfbhsJ9zkLiOsgmbqgkSU/Yl8i3gX4='     # generate with 'wg genkey' and PROTECT IT!
    post_ups:
      - sysctl -w net.ipv4.ip_forward=1
    wireguard_peers:
      - name: 'scw-fr-par-1-csgo'
        public_key: '+T53WioM6bnWd38WNamQYQkaTtZWmYj/tLE1AcB0jDo='   # generate with 'wg genkey' and PROTECT IT!
        allowed_ips: '10.9.0.2/32,192.168.1.0/24'
